# Generated by Django 5.0.14 on 2025-07-26 19:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad",
                    models.CharField(
                        help_text="Kategorinin adını girin (örn: Seminer, Konser, Spor)",
                        max_length=50,
                        unique=True,
                        verbose_name="Kategori Adı",
                    ),
                ),
                (
                    "aciklama",
                    models.TextField(
                        blank=True,
                        help_text="Kategori hakkında kısa bir açıklama",
                        verbose_name="Açıklama",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="calendar",
                        help_text="Bootstrap icon adı (örn: calendar, music, sport)",
                        max_length=50,
                        verbose_name="İkon",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategoriler",
                "ordering": ["ad"],
            },
        ),
        migrations.CreateModel(
            name="Etkinlik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "baslik",
                    models.CharField(
                        help_text="Etkinliğin başlığını girin",
                        max_length=200,
                        verbose_name="Etkinlik Başlığı",
                    ),
                ),
                (
                    "aciklama",
                    models.TextField(
                        help_text="Etkinlik hakkında detaylı açıklama",
                        verbose_name="Açıklama",
                    ),
                ),
                (
                    "baslangic_tarihi",
                    models.DateTimeField(
                        help_text="Etkinliğin başlayacağı tarih ve saat",
                        verbose_name="Başlangıç Tarihi",
                    ),
                ),
                (
                    "bitis_tarihi",
                    models.DateTimeField(
                        help_text="Etkinliğin biteceği tarih ve saat",
                        verbose_name="Bitiş Tarihi",
                    ),
                ),
                (
                    "yer",
                    models.CharField(
                        help_text="Etkinliğin yapılacağı yer (örn: Konferans Salonu)",
                        max_length=200,
                        verbose_name="Yer",
                    ),
                ),
                (
                    "adres",
                    models.TextField(
                        help_text="Etkinlik yerinin detaylı adresi",
                        verbose_name="Adres",
                    ),
                ),
                (
                    "maksimum_katilimci",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Etkinliğe katılabilecek maksimum kişi sayısı",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name="Maksimum Katılımcı",
                    ),
                ),
                (
                    "mevcut_katilimci",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Şu anda kayıtlı katılımcı sayısı",
                        verbose_name="Mevcut Katılımcı",
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("planlandi", "Planlandı"),
                            ("aktif", "Aktif"),
                            ("tamamlandi", "Tamamlandı"),
                            ("iptal", "İptal Edildi"),
                        ],
                        default="planlandi",
                        help_text="Etkinliğin mevcut durumu",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "ucret",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Etkinlik ücreti (ücretsiz ise boş bırakın)",
                        max_digits=10,
                        null=True,
                        verbose_name="Ücret",
                    ),
                ),
                (
                    "resim",
                    models.ImageField(
                        blank=True,
                        help_text="Etkinlik için bir resim yükleyin",
                        null=True,
                        upload_to="etkinlik_resimleri/",
                        verbose_name="Etkinlik Resmi",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(auto_now=True, verbose_name="Son Güncelleme"),
                ),
                (
                    "organizator",
                    models.ForeignKey(
                        help_text="Etkinliği organize eden kişi",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Organizatör",
                    ),
                ),
                (
                    "kategori",
                    models.ForeignKey(
                        help_text="Etkinliğin kategorisini seçin",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="etkinlikler.kategori",
                        verbose_name="Kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etkinlik",
                "verbose_name_plural": "Etkinlikler",
                "ordering": ["-baslangic_tarihi"],
            },
        ),
    ]
