# Generated by Django 5.0.14 on 2025-07-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etkinlikler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="etkinlik",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="Eventbrite gibi dış API'lerden gelen etkinlik ID'si",
                max_length=100,
                null=True,
                verbose_name="Dış API ID",
            ),
        ),
        migrations.AddField(
            model_name="etkinlik",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Etkinlik yerinin enlem koordinatı",
                max_digits=9,
                null=True,
                verbose_name="Enlem",
            ),
        ),
        migrations.AddField(
            model_name="etkinlik",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Etkinlik yerinin boylam koordinatı",
                max_digits=9,
                null=True,
                verbose_name="Boylam",
            ),
        ),
        migrations.AddField(
            model_name="etkinlik",
            name="source",
            field=models.CharField(
                choices=[
                    ("internal", "Yerel"),
                    ("eventbrite", "Eventbrite"),
                    ("ticketmaster", "Ticketmaster"),
                ],
                default="internal",
                help_text="Etkinliğin hangi kaynaktan geldiği",
                max_length=50,
                verbose_name="Kaynak",
            ),
        ),
    ]
