# Generated by Django 5.0.14 on 2025-07-26 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etkinlikler", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kayit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("beklemede", "Beklemede"),
                            ("onaylandi", "Onaylandı"),
                            ("reddedildi", "Reddedildi"),
                            ("iptal_edildi", "İptal Edildi"),
                            ("tamamlandi", "Tamamlandı"),
                        ],
                        default="beklemede",
                        help_text="Kayıt durumu",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "kayit_turu",
                    models.CharField(
                        choices=[
                            ("normal", "Normal Kayıt"),
                            ("vip", "VIP Kayıt"),
                            ("erken_kayit", "Erken Kayıt"),
                            ("indirimli", "İndirimli Kayıt"),
                        ],
                        default="normal",
                        help_text="Kayıt türü",
                        max_length=20,
                        verbose_name="Kayıt Türü",
                    ),
                ),
                (
                    "odendi",
                    models.BooleanField(
                        default=False,
                        help_text="Kayıt ücreti ödendi mi?",
                        verbose_name="Ödendi",
                    ),
                ),
                (
                    "odeme_tarihi",
                    models.DateTimeField(
                        blank=True,
                        help_text="Ödeme yapılan tarih",
                        null=True,
                        verbose_name="Ödeme Tarihi",
                    ),
                ),
                (
                    "odeme_yontemi",
                    models.CharField(
                        blank=True,
                        help_text="Kullanılan ödeme yöntemi",
                        max_length=50,
                        verbose_name="Ödeme Yöntemi",
                    ),
                ),
                (
                    "notlar",
                    models.TextField(
                        blank=True,
                        help_text="Kayıt hakkında ek notlar",
                        verbose_name="Notlar",
                    ),
                ),
                (
                    "kayit_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kayıt Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "etkinlik",
                    models.ForeignKey(
                        help_text="Kayıt olunan etkinlik",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="etkinlikler.etkinlik",
                        verbose_name="Etkinlik",
                    ),
                ),
                (
                    "katilimci",
                    models.ForeignKey(
                        help_text="Kayıt olan katılımcı",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Katılımcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kayıt",
                "verbose_name_plural": "Kayıtlar",
                "ordering": ["-kayit_tarihi"],
                "unique_together": {("katilimci", "etkinlik")},
            },
        ),
        migrations.CreateModel(
            name="KayitGecmisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eski_durum",
                    models.CharField(
                        choices=[
                            ("beklemede", "Beklemede"),
                            ("onaylandi", "Onaylandı"),
                            ("reddedildi", "Reddedildi"),
                            ("iptal_edildi", "İptal Edildi"),
                            ("tamamlandi", "Tamamlandı"),
                        ],
                        help_text="Önceki durum",
                        max_length=20,
                        verbose_name="Eski Durum",
                    ),
                ),
                (
                    "yeni_durum",
                    models.CharField(
                        choices=[
                            ("beklemede", "Beklemede"),
                            ("onaylandi", "Onaylandı"),
                            ("reddedildi", "Reddedildi"),
                            ("iptal_edildi", "İptal Edildi"),
                            ("tamamlandi", "Tamamlandı"),
                        ],
                        help_text="Yeni durum",
                        max_length=20,
                        verbose_name="Yeni Durum",
                    ),
                ),
                (
                    "notlar",
                    models.TextField(
                        blank=True,
                        help_text="Değişiklik hakkında notlar",
                        verbose_name="Notlar",
                    ),
                ),
                (
                    "degisiklik_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Değişiklik Tarihi"
                    ),
                ),
                (
                    "degistiren",
                    models.ForeignKey(
                        blank=True,
                        help_text="Değişikliği yapan kişi",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Değiştiren",
                    ),
                ),
                (
                    "kayit",
                    models.ForeignKey(
                        help_text="İlgili kayıt",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kayitlar.kayit",
                        verbose_name="Kayıt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kayıt Geçmişi",
                "verbose_name_plural": "Kayıt Geçmişleri",
                "ordering": ["-degisiklik_tarihi"],
            },
        ),
    ]
