# Generated by Django 5.0.14 on 2025-07-26 19:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Katilimci",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telefon",
                    models.CharField(
                        blank=True,
                        help_text="İletişim telefon numarası",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Telefon numarası geçerli formatta olmalıdır. Örnek: +905551234567",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Telefon",
                    ),
                ),
                (
                    "dogum_tarihi",
                    models.DateField(
                        blank=True,
                        help_text="Katılımcının doğum tarihi",
                        null=True,
                        verbose_name="Doğum Tarihi",
                    ),
                ),
                (
                    "adres",
                    models.TextField(
                        blank=True,
                        help_text="Katılımcının adres bilgisi",
                        verbose_name="Adres",
                    ),
                ),
                (
                    "sehir",
                    models.CharField(
                        blank=True,
                        help_text="Yaşadığı şehir",
                        max_length=50,
                        verbose_name="Şehir",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Katılımcı hakkında kısa bilgi",
                        verbose_name="Hakkında",
                    ),
                ),
                (
                    "profil_resmi",
                    models.ImageField(
                        blank=True,
                        help_text="Profil fotoğrafı",
                        null=True,
                        upload_to="profil_resimleri/",
                        verbose_name="Profil Resmi",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Kişisel website adresi",
                        verbose_name="Website",
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(
                        blank=True,
                        help_text="LinkedIn profil linki",
                        verbose_name="LinkedIn",
                    ),
                ),
                (
                    "twitter",
                    models.URLField(
                        blank=True,
                        help_text="Twitter profil linki",
                        verbose_name="Twitter",
                    ),
                ),
                (
                    "email_bildirim",
                    models.BooleanField(
                        default=True,
                        help_text="E-posta ile bildirim almak istiyor mu?",
                        verbose_name="E-posta Bildirimleri",
                    ),
                ),
                (
                    "sms_bildirim",
                    models.BooleanField(
                        default=False,
                        help_text="SMS ile bildirim almak istiyor mu?",
                        verbose_name="SMS Bildirimleri",
                    ),
                ),
                (
                    "kayit_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kayıt Tarihi"
                    ),
                ),
                (
                    "son_guncelleme",
                    models.DateTimeField(auto_now=True, verbose_name="Son Güncelleme"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Katılımcının kullanıcı hesabı",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Katılımcı",
                "verbose_name_plural": "Katılımcılar",
                "ordering": ["user__first_name", "user__last_name"],
            },
        ),
        migrations.CreateModel(
            name="KatilimciGrubu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad",
                    models.CharField(
                        help_text="Grubun adı",
                        max_length=100,
                        unique=True,
                        verbose_name="Grup Adı",
                    ),
                ),
                (
                    "aciklama",
                    models.TextField(
                        blank=True,
                        help_text="Grup hakkında açıklama",
                        verbose_name="Açıklama",
                    ),
                ),
                (
                    "renk",
                    models.CharField(
                        default="#007bff",
                        help_text="Grubun temsil rengi (hex kodu)",
                        max_length=7,
                        verbose_name="Renk",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="people",
                        help_text="Bootstrap icon adı",
                        max_length=50,
                        verbose_name="İkon",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "katilimcilar",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Bu gruba ait katılımcılar",
                        to="katilimcilar.katilimci",
                        verbose_name="Katılımcılar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Katılımcı Grubu",
                "verbose_name_plural": "Katılımcı Grupları",
                "ordering": ["ad"],
            },
        ),
    ]
