# Generated by Django 5.0.14 on 2025-07-26 19:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organizator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telefon",
                    models.CharField(
                        blank=True,
                        help_text="İletişim telefon numarası",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Telefon numarası geçerli formatta olmalıdır. Örnek: +905551234567",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Telefon",
                    ),
                ),
                (
                    "organizasyon_adi",
                    models.CharField(
                        blank=True,
                        help_text="Çalıştığı organizasyonun adı",
                        max_length=100,
                        verbose_name="Organizasyon Adı",
                    ),
                ),
                (
                    "pozisyon",
                    models.CharField(
                        blank=True,
                        help_text="Organizasyondaki pozisyonu",
                        max_length=100,
                        verbose_name="Pozisyon",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Organizasyon website adresi",
                        verbose_name="Website",
                    ),
                ),
                (
                    "adres",
                    models.TextField(
                        blank=True,
                        help_text="Organizasyon adresi",
                        verbose_name="Adres",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Organizatör hakkında kısa bilgi",
                        verbose_name="Hakkında",
                    ),
                ),
                (
                    "profil_resmi",
                    models.ImageField(
                        blank=True,
                        help_text="Profil fotoğrafı",
                        null=True,
                        upload_to="organizator_resimleri/",
                        verbose_name="Profil Resmi",
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(
                        blank=True,
                        help_text="LinkedIn profil linki",
                        verbose_name="LinkedIn",
                    ),
                ),
                (
                    "twitter",
                    models.URLField(
                        blank=True,
                        help_text="Twitter profil linki",
                        verbose_name="Twitter",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Organizatör hesabı doğrulanmış mı?",
                        verbose_name="Doğrulanmış",
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False,
                        help_text="Premium organizatör mü?",
                        verbose_name="Premium",
                    ),
                ),
                (
                    "kayit_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kayıt Tarihi"
                    ),
                ),
                (
                    "son_guncelleme",
                    models.DateTimeField(auto_now=True, verbose_name="Son Güncelleme"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Organizatörün kullanıcı hesabı",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizatör",
                "verbose_name_plural": "Organizatörler",
                "ordering": ["user__first_name", "user__last_name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizatorGrubu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad",
                    models.CharField(
                        help_text="Grubun adı",
                        max_length=100,
                        unique=True,
                        verbose_name="Grup Adı",
                    ),
                ),
                (
                    "aciklama",
                    models.TextField(
                        blank=True,
                        help_text="Grup hakkında açıklama",
                        verbose_name="Açıklama",
                    ),
                ),
                (
                    "renk",
                    models.CharField(
                        default="#28a745",
                        help_text="Grubun temsil rengi (hex kodu)",
                        max_length=7,
                        verbose_name="Renk",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="people-fill",
                        help_text="Bootstrap icon adı",
                        max_length=50,
                        verbose_name="İkon",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "organizatorler",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Bu gruba ait organizatörler",
                        to="organizatorler.organizator",
                        verbose_name="Organizatörler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizatör Grubu",
                "verbose_name_plural": "Organizatör Grupları",
                "ordering": ["ad"],
            },
        ),
    ]
